name: Testing Discussion Events

on:
  discussion:
    types: [created, edited, deleted, pinned, unpinned, labeled, unlabeled, category_changed]
    categories:
      - Release
      - Draft

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Test out discussion events triggering
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          echo This is triggered!
          echo "$GITHUB_CONTEXT"
      - name: Check if changes are done from either Drafts/Release categories
        run: |
          discussion_category="${{ github.event.discussion.category.slug }}"
          echo "$discussion_category"
          if [ "$discussion_category" = "drafts" -o "$discussion_category" = "release" ]; then
            echo "it's okay"
          else
            echo "it's not okay, failing.."
          fi
