name: Posts Updater

on:
  discussion:
    types: [created, edited, deleted, pinned, unpinned, labeled, unlabeled, category_changed]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check if changes are done from either Drafts/Release discussion categories
        env:
          VERCEL_DEPLOY_TOKEN: ${{ secrets.VERCEL_DEPLOY_TOKEN }}
        run: |
          discussion_category="${{ github.event.discussion.category.slug }}"
          if [ "$discussion_category" = "drafts" -o "$discussion_category" = "release" ]; then
            echo "Matched Draft/Release discussion category, triggering a deployment.."
            curl -X POST "https://api.vercel.com/v1/integrations/deploy/prj_S1lsvmlFHFz7NSzuezqarPtuC8FZ/$VERCEL_DEPLOY_TOKEN"
            echo "Deployment triggered successfully!"
          else
            echo "Out of scope discussion category, failing.."
            exit 1
          fi
