name: Testing Discussion Events

on:
  discussion:
    types: [created, edited, deleted, pinned, unpinned, labeled, unlabeled, category_changed]
    categories:
      - Release
      - Draft

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Test out discussion events triggering
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          echo This is triggered!
          echo "$GITHUB_CONTEXT"
