name: Testing Discussion Events

on:
  discussion:
    types: [created, edited, deleted, pinned, unpinned, labeled, unlabeled, category_changed]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check if changes are done from either Drafts/Release categories
        env:
          VERCEL_DEPLOY_TOKEN: ${{ secrets.VERCEL_DEPLOY_TOKEN }}
        run: |
          discussion_category="${{ github.event.discussion.category.slug }}"
          echo "$discussion_category"
          if [ "$discussion_category" = "drafts" -o "$discussion_category" = "release" ]; then
            echo "it's okay"
            curl -X POST "https://api.vercel.com/v1/integrations/deploy/prj_S1lsvmlFHFz7NSzuezqarPtuC8FZ/$VERCEL_DEPLOY_TOKEN"
          else
            echo "it's not okay, failing.."
            exit 1
          fi
